// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ts.Infra.ShopIn.Data.Context;

#nullable disable

namespace Ts.Infra.ShopIn.Data.Migrations
{
    [DbContext(typeof(ShopInDbContext))]
    [Migration("20260504184334_One")]
    partial class One
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "dbo");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlogLink")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("BlogSource")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar");

                    b.Property<string>("BlogWorkerId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<byte[]>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("CreatedOn")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Keyword1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Keyword2")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Keyword3")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Keyword4")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Keyword5")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("MainImage")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("MainImageSource")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar");

                    b.Property<string>("MetaDescription")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar");

                    b.Property<string>("PublishedById")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("PublishedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar");

                    b.Property<string>("UpdatedById")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BlogLink")
                        .IsUnique();

                    b.HasIndex("CreatedOn");

                    b.HasIndex("Keyword1");

                    b.HasIndex("Keyword2");

                    b.HasIndex("Keyword3");

                    b.HasIndex("Keyword4");

                    b.HasIndex("Keyword5");

                    b.HasIndex("Title");

                    b.HasIndex("UpdatedOn");

                    b.ToTable("Blogs", "dbo");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.BlogImage", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("BlogId");

                    b.Property<byte[]>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("CreatedOn")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedById")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("UpdatedOn");

                    b.ToTable("BlogImages", "dbo");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.BlogView", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("BlogId");

                    b.Property<DateTime>("LastViewedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalViews")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LastViewedOn");

                    b.ToTable("BlogViews", "dbo");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.Cart", b =>
                {
                    b.Property<int>("ProductDetailId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<byte[]>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<DateTime?>("CreatedOn")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ItemCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.HasKey("ProductDetailId", "UserId");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("UserId");

                    b.ToTable("Carts", "dbo");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.ClientUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("CanLogin")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<int?>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(16)
                        .HasColumnType("varchar");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneCode")
                        .HasMaxLength(5)
                        .HasColumnType("varchar");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileImageName")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("ProfileImageName")
                        .IsUnique()
                        .HasFilter("[ProfileImageName] IS NOT NULL");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("FirstName", "LastName");

                    b.ToTable("AspNetUsers", "dbo");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.LoginLog", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("LoggedOn")
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LoginLogs", "dbo");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.NextOrderSetting", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<int>("NextOrderNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NextOrderSettings", "dbo");

                    b.HasData(
                        new
                        {
                            Id = "d95ecbe5-b708-4252-86be-2631fc6634b3",
                            NextOrderNumber = 1
                        });
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.NextUserSetting", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<int>("NextUserNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NextUserSettings", "dbo");

                    b.HasData(
                        new
                        {
                            Id = "d95ecbe5-b708-4252-86be-2631fc6634b2",
                            NextUserNumber = 1
                        });
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<int>("CurrencyTypeId")
                        .HasColumnType("int");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("OrderedOn")
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentModeId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("TotalItemCount")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber");

                    b.HasIndex("OrderedOn");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", "dbo");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedOn")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrencyTypeId")
                        .HasColumnType("int");

                    b.Property<int>("DeliveryPolicyId")
                        .HasColumnType("int");

                    b.Property<int>("ExchangePolicyId")
                        .HasColumnType("int");

                    b.Property<int>("ItemCount")
                        .HasColumnType("int");

                    b.Property<decimal>("ItemPrice")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductDetailId")
                        .HasColumnType("int");

                    b.Property<int>("ReturnPolicyId")
                        .HasColumnType("int");

                    b.Property<int>("ShopCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductDetailId");

                    b.HasIndex("UpdatedOn");

                    b.ToTable("OrderDetails", "dbo");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.OrderDetailStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("OrderDetailId");

                    b.Property<string>("OrderStatuses")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrderDetailStatusHistories", "dbo");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("OrderId");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime?>("CreatedOn")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrencyTypeId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentGatewayTypeId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatusId")
                        .HasColumnType("int");

                    b.Property<decimal>("Razorpay_Amount_Refunded")
                        .HasColumnType("decimal(18,3)");

                    b.Property<long>("Razorpay_Created_At")
                        .HasColumnType("bigint");

                    b.Property<string>("Razorpay_Method")
                        .HasMaxLength(150)
                        .HasColumnType("varchar");

                    b.Property<string>("Razorpay_Order_Id")
                        .HasMaxLength(450)
                        .HasColumnType("varchar");

                    b.Property<string>("Razorpay_Payment_Id")
                        .HasMaxLength(450)
                        .HasColumnType("varchar");

                    b.Property<string>("Razorpay_Refund_Status")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("UpdatedOn");

                    b.ToTable("Payments", "dbo");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.PaymentStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("PaymentId");

                    b.Property<string>("PaymentStatuses")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PaymentStatusHistories", "dbo");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("CreatedOn")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("MainImage")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("ProductWorkerId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("PublishedById")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("PublishedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar");

                    b.Property<string>("UpdatedById")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.HasIndex("UpdatedOn");

                    b.ToTable("Products", "dbo");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.ProductDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("CreatedOn")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.Property<int>("DeliveryPolicyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExchangePolicyId")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Keyword1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Keyword2")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Keyword3")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Keyword4")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Keyword5")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("MainImage")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("MetaDescription")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar");

                    b.Property<decimal>("Mrp")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("ProductDetailLink")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("ProductDetailWorkerId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("PublishedById")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("PublishedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReturnPolicyId")
                        .HasColumnType("int");

                    b.Property<int>("ShopCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar");

                    b.Property<string>("UpdatedById")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("Keyword1");

                    b.HasIndex("Keyword2");

                    b.HasIndex("Keyword3");

                    b.HasIndex("Keyword4");

                    b.HasIndex("Keyword5");

                    b.HasIndex("ProductDetailLink")
                        .IsUnique();

                    b.HasIndex("Title");

                    b.HasIndex("UpdatedOn");

                    b.ToTable("ProductDetails", "dbo");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.ProductDetailDocument", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ProductDetailId");

                    b.Property<byte[]>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("CreatedOn")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("varchar(450)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedById")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("UpdatedOn");

                    b.ToTable("ProductDetailDocuments", "dbo");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.ProductDetailImage", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ProductId");

                    b.Property<byte[]>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("CreatedOn")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedById")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("UpdatedOn");

                    b.ToTable("ProductDetailImages", "dbo");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.ProductDetailView", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ProductId");

                    b.Property<DateTime>("LastViewedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalViews")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LastViewedOn");

                    b.ToTable("ProductDetailViews", "dbo");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ProductId");

                    b.Property<byte[]>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("CreatedOn")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedById")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("UpdatedOn");

                    b.ToTable("ProductImages", "dbo");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.ProductVariant", b =>
                {
                    b.Property<int>("ProductDetailId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("ProductDetailId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVariants", "dbo");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("RefreshReloginId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RefreshTokens", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Ts.ShopIn.Domain.Models.ClientUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Ts.ShopIn.Domain.Models.ClientUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ts.ShopIn.Domain.Models.ClientUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Ts.ShopIn.Domain.Models.ClientUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.BlogImage", b =>
                {
                    b.HasOne("Ts.ShopIn.Domain.Models.Blog", "Blog")
                        .WithOne("BlogImage")
                        .HasForeignKey("Ts.ShopIn.Domain.Models.BlogImage", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.BlogView", b =>
                {
                    b.HasOne("Ts.ShopIn.Domain.Models.Blog", "Blog")
                        .WithOne("BlogView")
                        .HasForeignKey("Ts.ShopIn.Domain.Models.BlogView", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.Cart", b =>
                {
                    b.HasOne("Ts.ShopIn.Domain.Models.ProductDetail", "ProductDetail")
                        .WithMany("Carts")
                        .HasForeignKey("ProductDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ts.ShopIn.Domain.Models.ClientUser", "CartAddedBy")
                        .WithMany("CartAddedByUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartAddedBy");

                    b.Navigation("ProductDetail");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.LoginLog", b =>
                {
                    b.HasOne("Ts.ShopIn.Domain.Models.ClientUser", "LoggedInBy")
                        .WithMany("CreatedLoginLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoggedInBy");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.Order", b =>
                {
                    b.HasOne("Ts.ShopIn.Domain.Models.ClientUser", "OrderedBy")
                        .WithMany("OrderAddedByUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("OrderedBy");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.OrderDetail", b =>
                {
                    b.HasOne("Ts.ShopIn.Domain.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ts.ShopIn.Domain.Models.ProductDetail", "ProductDetail")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductDetailId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Order");

                    b.Navigation("ProductDetail");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.OrderDetailStatusHistory", b =>
                {
                    b.HasOne("Ts.ShopIn.Domain.Models.OrderDetail", "OrderDetail")
                        .WithOne("OrderStatusHistory")
                        .HasForeignKey("Ts.ShopIn.Domain.Models.OrderDetailStatusHistory", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderDetail");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.Payment", b =>
                {
                    b.HasOne("Ts.ShopIn.Domain.Models.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("Ts.ShopIn.Domain.Models.Payment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.PaymentStatusHistory", b =>
                {
                    b.HasOne("Ts.ShopIn.Domain.Models.Payment", "Payment")
                        .WithOne("PaymentStatusHistory")
                        .HasForeignKey("Ts.ShopIn.Domain.Models.PaymentStatusHistory", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.ProductDetailDocument", b =>
                {
                    b.HasOne("Ts.ShopIn.Domain.Models.ProductDetail", "ProductDetail")
                        .WithOne("ProductDetailDocument")
                        .HasForeignKey("Ts.ShopIn.Domain.Models.ProductDetailDocument", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductDetail");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.ProductDetailImage", b =>
                {
                    b.HasOne("Ts.ShopIn.Domain.Models.ProductDetail", "ProductDetail")
                        .WithOne("ProductDetailImage")
                        .HasForeignKey("Ts.ShopIn.Domain.Models.ProductDetailImage", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductDetail");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.ProductDetailView", b =>
                {
                    b.HasOne("Ts.ShopIn.Domain.Models.ProductDetail", "ProductDetail")
                        .WithOne("ProductDetailView")
                        .HasForeignKey("Ts.ShopIn.Domain.Models.ProductDetailView", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductDetail");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.ProductImage", b =>
                {
                    b.HasOne("Ts.ShopIn.Domain.Models.Product", "Product")
                        .WithOne("ProductImage")
                        .HasForeignKey("Ts.ShopIn.Domain.Models.ProductImage", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.ProductVariant", b =>
                {
                    b.HasOne("Ts.ShopIn.Domain.Models.ProductDetail", "ProductDetail")
                        .WithOne("ProductVariant")
                        .HasForeignKey("Ts.ShopIn.Domain.Models.ProductVariant", "ProductDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ts.ShopIn.Domain.Models.Product", "Product")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductDetail");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.RefreshToken", b =>
                {
                    b.HasOne("Ts.ShopIn.Domain.Models.ClientUser", "User")
                        .WithOne("CreatedRefreshToken")
                        .HasForeignKey("Ts.ShopIn.Domain.Models.RefreshToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.Blog", b =>
                {
                    b.Navigation("BlogImage");

                    b.Navigation("BlogView");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.ClientUser", b =>
                {
                    b.Navigation("CartAddedByUsers");

                    b.Navigation("CreatedLoginLogs");

                    b.Navigation("CreatedRefreshToken");

                    b.Navigation("OrderAddedByUsers");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.OrderDetail", b =>
                {
                    b.Navigation("OrderStatusHistory");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.Payment", b =>
                {
                    b.Navigation("PaymentStatusHistory");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.Product", b =>
                {
                    b.Navigation("ProductImage");

                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("Ts.ShopIn.Domain.Models.ProductDetail", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("OrderDetails");

                    b.Navigation("ProductDetailDocument");

                    b.Navigation("ProductDetailImage");

                    b.Navigation("ProductDetailView");

                    b.Navigation("ProductVariant");
                });
#pragma warning restore 612, 618
        }
    }
}
