// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ts.Infra.Data.Context;

#nullable disable

namespace Ts.Infra.Data.Migrations
{
    [DbContext(typeof(TsIdentityDbContext))]
    [Migration("20260504184143_One")]
    partial class One
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "ViewUse",
                            ClaimValue = "true",
                            UserId = "214eccb4-402e-4004-807b-80e011db75d2"
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "CreateUse",
                            ClaimValue = "true",
                            UserId = "214eccb4-402e-4004-807b-80e011db75d2"
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "UpdateUse",
                            ClaimValue = "true",
                            UserId = "214eccb4-402e-4004-807b-80e011db75d2"
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "UpdateUserPrivilegeUse",
                            ClaimValue = "true",
                            UserId = "214eccb4-402e-4004-807b-80e011db75d2"
                        },
                        new
                        {
                            Id = 5,
                            ClaimType = "UpdateUserEmailUse",
                            ClaimValue = "true",
                            UserId = "214eccb4-402e-4004-807b-80e011db75d2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "dbo");

                    b.HasData(
                        new
                        {
                            UserId = "214eccb4-402e-4004-807b-80e011db75d2",
                            RoleId = "3f81e050-9991-4913-bee1-7105a3108de3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "dbo");
                });

            modelBuilder.Entity("Ts.Domain.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar");

                    b.Property<string>("Address2")
                        .HasMaxLength(450)
                        .HasColumnType("varchar");

                    b.Property<byte[]>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("CreatedOn")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PostOfficeId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedById")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("PostOfficeId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses", "dbo");
                });

            modelBuilder.Entity("Ts.Domain.Models.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", "dbo");

                    b.HasData(
                        new
                        {
                            Id = "3f81e050-9991-4913-bee1-7105a3108de3",
                            IsActive = true,
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "3f81e050-9991-4913-bee1-7105a3108de4",
                            IsActive = true,
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        },
                        new
                        {
                            Id = "3f81e050-9991-4913-bee1-7105a3108de5",
                            IsActive = true,
                            Name = "DotInSiteUser",
                            NormalizedName = "DOTINSITEUSER"
                        },
                        new
                        {
                            Id = "3f81e050-9991-4913-bee1-7105a3108de6",
                            IsActive = true,
                            Name = "DotComSiteUser",
                            NormalizedName = "DOTCOMSITEUSER"
                        },
                        new
                        {
                            Id = "3f81e050-9991-4913-bee1-7105a3108de7",
                            IsActive = true,
                            Name = "ShopInUser",
                            NormalizedName = "SHOPINUSER"
                        },
                        new
                        {
                            Id = "3f81e050-9991-4913-bee1-7105a3108de8",
                            IsActive = true,
                            Name = "EmployeeShopIn",
                            NormalizedName = "EMPLOYEESHOPIN"
                        });
                });

            modelBuilder.Entity("Ts.Domain.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("CanLogin")
                        .HasColumnType("bit");

                    b.Property<bool>("ChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedById")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("CreatedOn")
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<int?>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(16)
                        .HasColumnType("varchar");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneCode")
                        .HasMaxLength(5)
                        .HasColumnType("varchar");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileImageName")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedById")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("GenderId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("ProfileImageName")
                        .IsUnique()
                        .HasFilter("[ProfileImageName] IS NOT NULL");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("FirstName", "LastName");

                    b.ToTable("AspNetUsers", "dbo");

                    b.HasData(
                        new
                        {
                            Id = "214eccb4-402e-4004-807b-80e011db75d2",
                            AccessFailedCount = 0,
                            CanLogin = true,
                            ChangePassword = true,
                            ConcurrencyStamp = "908a4aed-bf84-4558-b3b0-1814fd050858",
                            CreatedOn = new DateTime(2022, 10, 20, 12, 34, 26, 469, DateTimeKind.Unspecified).AddTicks(4431),
                            Email = "demoemailddj@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Demo",
                            IsActive = true,
                            LastName = "D",
                            LockoutEnabled = true,
                            NormalizedEmail = "DEMOEMAILDDJ@GMAIL.COM",
                            NormalizedUserName = "DEM20231",
                            PasswordHash = "AQAAAAEAACcQAAAAELdnlJJYejLvTetcJEEkiCE7ENyDx6NG+qynlhYqXLvsxON0hriLoPA1mMtc8MUGQw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6ded5a7c-bacf-48db-a928-0b5f0dca8aee",
                            TwoFactorEnabled = false,
                            UserName = "DEM20231"
                        });
                });

            modelBuilder.Entity("Ts.Domain.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("CreatedOn")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("UpdatedById")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdatedById");

                    b.HasIndex("UpdatedOn");

                    b.ToTable("Categories", "dbo");
                });

            modelBuilder.Entity("Ts.Domain.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar")
                        .IsFixedLength();

                    b.Property<string>("Code3")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar")
                        .IsFixedLength();

                    b.Property<byte[]>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("CreatedOn")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("UpdatedById")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code2")
                        .IsUnique();

                    b.HasIndex("Code3")
                        .IsUnique();

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdatedById");

                    b.HasIndex("UpdatedOn");

                    b.ToTable("Countries", "dbo");
                });

            modelBuilder.Entity("Ts.Domain.Models.CurrencyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Letter")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar")
                        .IsFixedLength();

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.HasIndex("Letter")
                        .IsUnique();

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("CurrencyTypes", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Letter = "INR",
                            Symbol = "₹"
                        });
                });

            modelBuilder.Entity("Ts.Domain.Models.DeliveryPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeliveryInDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DeliveryPolicies", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeliveryInDays = 15,
                            Name = "Downloadable15Days",
                            Title = "Download will be available for 15 days"
                        });
                });

            modelBuilder.Entity("Ts.Domain.Models.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("CreatedOn")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedById")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("StateId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("UpdatedOn");

                    b.ToTable("Districts", "dbo");
                });

            modelBuilder.Entity("Ts.Domain.Models.ExchangePolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExchangeInDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ExchangePolicies", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExchangeInDays = 0,
                            Name = "No-Exchange"
                        });
                });

            modelBuilder.Entity("Ts.Domain.Models.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genders", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Male"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Female"
                        },
                        new
                        {
                            Id = 3,
                            Name = "TransGender"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Both"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Unknown"
                        });
                });

            modelBuilder.Entity("Ts.Domain.Models.LoginLog", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("LoggedOn")
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LoginLogs", "dbo");
                });

            modelBuilder.Entity("Ts.Domain.Models.NextUserSetting", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<int>("NextUserNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NextUserSettings", "dbo");

                    b.HasData(
                        new
                        {
                            Id = "d95ecbe5-b708-4252-86be-2631fc6634b1",
                            NextUserNumber = 2
                        });
                });

            modelBuilder.Entity("Ts.Domain.Models.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("OrderStatuses", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Order-Initiated"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Order-Completed"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Payment-Pending"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Payment-Refunded"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Payment-Failed"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Payment-Refund-In-Process"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Payment-Refund-Failed"
                        });
                });

            modelBuilder.Entity("Ts.Domain.Models.PaymentGatewayType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PaymentGatewayTypes", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Razorpay"
                        });
                });

            modelBuilder.Entity("Ts.Domain.Models.PaymentMode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PaymentModes", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Online"
                        });
                });

            modelBuilder.Entity("Ts.Domain.Models.PaymentStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<int>("PaymentGatewayTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PaymentGatewayTypeId");

                    b.ToTable("PaymentStatuses", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "created",
                            PaymentGatewayTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "authorized",
                            PaymentGatewayTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "captured",
                            PaymentGatewayTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "refunded",
                            PaymentGatewayTypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "failed",
                            PaymentGatewayTypeId = 1
                        });
                });

            modelBuilder.Entity("Ts.Domain.Models.PostOffice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("CreatedOn")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar")
                        .IsFixedLength();

                    b.Property<string>("UpdatedById")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("DistrictId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdatedById");

                    b.HasIndex("UpdatedOn");

                    b.ToTable("PostOffices", "dbo");
                });

            modelBuilder.Entity("Ts.Domain.Models.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("RefreshReloginId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RefreshTokens", "dbo");
                });

            modelBuilder.Entity("Ts.Domain.Models.ReturnPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<int>("ReturnInDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ReturnPolicies", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "No-Return",
                            ReturnInDays = 0
                        });
                });

            modelBuilder.Entity("Ts.Domain.Models.ShopCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("CreatedOn")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("UpdatedById")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdatedById");

                    b.HasIndex("UpdatedOn");

                    b.ToTable("ShopCategories", "dbo");
                });

            modelBuilder.Entity("Ts.Domain.Models.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar")
                        .IsFixedLength();

                    b.Property<byte[]>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("CreatedOn")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("UpdatedById")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code2")
                        .IsUnique();

                    b.HasIndex("CountryId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdatedById");

                    b.HasIndex("UpdatedOn");

                    b.ToTable("States", "dbo");
                });

            modelBuilder.Entity("Ts.Domain.Models.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("CreatedOn")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("UpdatedById")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdatedById");

                    b.HasIndex("UpdatedOn");

                    b.ToTable("SubCategories", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Ts.Domain.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Ts.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Ts.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Ts.Domain.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ts.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Ts.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ts.Domain.Models.Address", b =>
                {
                    b.HasOne("Ts.Domain.Models.ApplicationUser", "CreatedBy")
                        .WithMany("CreatedAddresses")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ts.Domain.Models.PostOffice", "PostOffice")
                        .WithMany("Addresses")
                        .HasForeignKey("PostOfficeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ts.Domain.Models.ApplicationUser", "UpdatedBy")
                        .WithMany("UpdatedAddresses")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Ts.Domain.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("CreatedBy");

                    b.Navigation("PostOffice");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Ts.Domain.Models.ApplicationUser", b =>
                {
                    b.HasOne("Ts.Domain.Models.ApplicationUser", "CreatedBy")
                        .WithMany("CreatedApplicationUsers")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Ts.Domain.Models.Gender", "Gender")
                        .WithMany("ApplicationUsers")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Ts.Domain.Models.ApplicationUser", "UpdatedBy")
                        .WithMany("UpdatedApplicationUsers")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedBy");

                    b.Navigation("Gender");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Ts.Domain.Models.Category", b =>
                {
                    b.HasOne("Ts.Domain.Models.ApplicationUser", "CreatedBy")
                        .WithMany("CreatedCategories")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ts.Domain.Models.ApplicationUser", "UpdatedBy")
                        .WithMany("UpdatedCategories")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Ts.Domain.Models.Country", b =>
                {
                    b.HasOne("Ts.Domain.Models.ApplicationUser", "CreatedBy")
                        .WithMany("CreatedCountries")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ts.Domain.Models.ApplicationUser", "UpdatedBy")
                        .WithMany("UpdatedCountries")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Ts.Domain.Models.District", b =>
                {
                    b.HasOne("Ts.Domain.Models.ApplicationUser", "CreatedBy")
                        .WithMany("CreatedDistricts")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ts.Domain.Models.State", "State")
                        .WithMany("Districts")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ts.Domain.Models.ApplicationUser", "UpdatedBy")
                        .WithMany("UpdatedDistricts")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedBy");

                    b.Navigation("State");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Ts.Domain.Models.LoginLog", b =>
                {
                    b.HasOne("Ts.Domain.Models.ApplicationUser", "LoggedInBy")
                        .WithMany("CreatedLoginLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoggedInBy");
                });

            modelBuilder.Entity("Ts.Domain.Models.PaymentStatus", b =>
                {
                    b.HasOne("Ts.Domain.Models.PaymentGatewayType", "PaymentGatewayType")
                        .WithMany("PaymentStatuses")
                        .HasForeignKey("PaymentGatewayTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentGatewayType");
                });

            modelBuilder.Entity("Ts.Domain.Models.PostOffice", b =>
                {
                    b.HasOne("Ts.Domain.Models.ApplicationUser", "CreatedBy")
                        .WithMany("CreatedPostOffices")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ts.Domain.Models.District", "District")
                        .WithMany("PostOffices")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ts.Domain.Models.ApplicationUser", "UpdatedBy")
                        .WithMany("UpdatedPostOffices")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedBy");

                    b.Navigation("District");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Ts.Domain.Models.RefreshToken", b =>
                {
                    b.HasOne("Ts.Domain.Models.ApplicationUser", "User")
                        .WithOne("CreatedRefreshToken")
                        .HasForeignKey("Ts.Domain.Models.RefreshToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ts.Domain.Models.ShopCategory", b =>
                {
                    b.HasOne("Ts.Domain.Models.ApplicationUser", "CreatedBy")
                        .WithMany("CreatedShopCategories")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ts.Domain.Models.ApplicationUser", "UpdatedBy")
                        .WithMany("UpdatedShopCategories")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Ts.Domain.Models.State", b =>
                {
                    b.HasOne("Ts.Domain.Models.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ts.Domain.Models.ApplicationUser", "CreatedBy")
                        .WithMany("CreatedStates")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ts.Domain.Models.ApplicationUser", "UpdatedBy")
                        .WithMany("UpdatedStates")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Country");

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Ts.Domain.Models.SubCategory", b =>
                {
                    b.HasOne("Ts.Domain.Models.ApplicationUser", "CreatedBy")
                        .WithMany("CreatedSubCategories")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ts.Domain.Models.ApplicationUser", "UpdatedBy")
                        .WithMany("UpdatedSubCategories")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Ts.Domain.Models.ApplicationUser", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("CreatedAddresses");

                    b.Navigation("CreatedApplicationUsers");

                    b.Navigation("CreatedCategories");

                    b.Navigation("CreatedCountries");

                    b.Navigation("CreatedDistricts");

                    b.Navigation("CreatedLoginLogs");

                    b.Navigation("CreatedPostOffices");

                    b.Navigation("CreatedRefreshToken");

                    b.Navigation("CreatedShopCategories");

                    b.Navigation("CreatedStates");

                    b.Navigation("CreatedSubCategories");

                    b.Navigation("UpdatedAddresses");

                    b.Navigation("UpdatedApplicationUsers");

                    b.Navigation("UpdatedCategories");

                    b.Navigation("UpdatedCountries");

                    b.Navigation("UpdatedDistricts");

                    b.Navigation("UpdatedPostOffices");

                    b.Navigation("UpdatedShopCategories");

                    b.Navigation("UpdatedStates");

                    b.Navigation("UpdatedSubCategories");
                });

            modelBuilder.Entity("Ts.Domain.Models.Country", b =>
                {
                    b.Navigation("States");
                });

            modelBuilder.Entity("Ts.Domain.Models.District", b =>
                {
                    b.Navigation("PostOffices");
                });

            modelBuilder.Entity("Ts.Domain.Models.Gender", b =>
                {
                    b.Navigation("ApplicationUsers");
                });

            modelBuilder.Entity("Ts.Domain.Models.PaymentGatewayType", b =>
                {
                    b.Navigation("PaymentStatuses");
                });

            modelBuilder.Entity("Ts.Domain.Models.PostOffice", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("Ts.Domain.Models.State", b =>
                {
                    b.Navigation("Districts");
                });
#pragma warning restore 612, 618
        }
    }
}
