<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<!--<Nullable>enable</Nullable>-->
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="8.0.4" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Ts.Application\Ts.Application.csproj" />
		<ProjectReference Include="..\Ts.DotCom.Service\Ts.DotCom.Service.csproj" />
		<ProjectReference Include="..\Ts.DotIn.Service\Ts.DotIn.Service.csproj" />
		<ProjectReference Include="..\Ts.Infra.Data\Ts.Infra.Data.csproj" />
		<ProjectReference Include="..\Ts.Infra.DotCom.Data\Ts.Infra.DotCom.Data.csproj" />
		<ProjectReference Include="..\Ts.Infra.DotIn.Data\Ts.Infra.DotIn.Data.csproj" />
		<ProjectReference Include="..\Ts.Infra.ShopIn.Data\Ts.Infra.ShopIn.Data.csproj" />
		<ProjectReference Include="..\Ts.ShopIn.Service\Ts.ShopIn.Service.csproj" />
	</ItemGroup>

</Project>
