<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<!--<Nullable>enable</Nullable>-->
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="WebMarkupMin.AspNetCore8" Version="2.16.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Ts.DotIn.Client\Ts.DotIn.Client.csproj" />
	</ItemGroup>

</Project>
