<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<!--<Nullable>enable</Nullable>-->
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Ts.Common.Constant\Ts.Common.Constant.csproj" />
		<ProjectReference Include="..\TS.ShopIn.Domain\Ts.ShopIn.Domain.csproj" />
	</ItemGroup>

</Project>
