<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<!--<Nullable>enable</Nullable>-->
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Ts.Client\Ts.Client.csproj" />
		<ProjectReference Include="..\Ts.ShopIn.Dto\Ts.ShopIn.Dto.csproj" />
	</ItemGroup>

</Project>
