<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<!--<Nullable>enable</Nullable>-->
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Ts.DotCom.Domain\Ts.DotCom.Domain.csproj" />
		<ProjectReference Include="..\Ts.DotCom.Dto\Ts.DotCom.Dto.csproj" />
		<ProjectReference Include="..\Ts.Service\Ts.Service.csproj" />
	</ItemGroup>

</Project>
