// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ts.Infra.DotCom.Data.Context;

#nullable disable

namespace Ts.Infra.DotCom.Data.Migrations
{
    [DbContext(typeof(DotComDbContext))]
    [Migration("20260504184242_One")]
    partial class One
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ts.DotCom.Domain.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<byte[]>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("CreatedOn")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Keyword1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Keyword2")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Keyword3")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Keyword4")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Keyword5")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("MainImage")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("MainImageSource")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar");

                    b.Property<string>("MetaDescription")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar");

                    b.Property<string>("PostLink")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("PostSource")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar");

                    b.Property<string>("PostWorkerId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("PublishedById")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("PublishedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar");

                    b.Property<string>("UpdatedById")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("Keyword1");

                    b.HasIndex("Keyword2");

                    b.HasIndex("Keyword3");

                    b.HasIndex("Keyword4");

                    b.HasIndex("Keyword5");

                    b.HasIndex("PostLink")
                        .IsUnique();

                    b.HasIndex("Title");

                    b.HasIndex("UpdatedOn");

                    b.ToTable("Posts", "dbo");
                });

            modelBuilder.Entity("Ts.DotCom.Domain.Models.PostImage", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("PostId");

                    b.Property<byte[]>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("CreatedOn")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedById")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("UpdatedOn");

                    b.ToTable("PostImages", "dbo");
                });

            modelBuilder.Entity("Ts.DotCom.Domain.Models.PostRelative", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("PostId");

                    b.Property<byte[]>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("CreatedOn")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RelativeUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedById")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("UpdatedOn");

                    b.ToTable("PostRelatives", "dbo");
                });

            modelBuilder.Entity("Ts.DotCom.Domain.Models.PostView", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("PostId");

                    b.Property<DateTime>("LastViewedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalViews")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LastViewedOn");

                    b.ToTable("PostViews", "dbo");
                });

            modelBuilder.Entity("Ts.DotCom.Domain.Models.Story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("CreatedOn")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Keyword1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Keyword2")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Keyword3")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Keyword4")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Keyword5")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("MainDescription")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar");

                    b.Property<string>("MainImage")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("MainImageSource")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar");

                    b.Property<string>("MetaDescription")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar");

                    b.Property<string>("PublishedById")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("PublishedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("StoryLink")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("StorySource")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar");

                    b.Property<string>("StoryWorkerId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar");

                    b.Property<string>("UpdatedById")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("Keyword1");

                    b.HasIndex("Keyword2");

                    b.HasIndex("Keyword3");

                    b.HasIndex("Keyword4");

                    b.HasIndex("Keyword5");

                    b.HasIndex("StoryLink")
                        .IsUnique();

                    b.HasIndex("Title");

                    b.HasIndex("UpdatedOn");

                    b.ToTable("Stories", "dbo");
                });

            modelBuilder.Entity("Ts.DotCom.Domain.Models.StoryImage", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("StoryId");

                    b.Property<byte[]>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("CreatedOn")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedById")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("UpdatedOn");

                    b.ToTable("StoryImages", "dbo");
                });

            modelBuilder.Entity("Ts.DotCom.Domain.Models.StoryRelative", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("StoryId");

                    b.Property<byte[]>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("CreatedOn")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RelativeUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedById")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasMaxLength(7)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("UpdatedOn");

                    b.ToTable("StoryRelatives", "dbo");
                });

            modelBuilder.Entity("Ts.DotCom.Domain.Models.StoryView", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("StoryId");

                    b.Property<DateTime>("LastViewedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalViews")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LastViewedOn");

                    b.ToTable("StoryViews", "dbo");
                });

            modelBuilder.Entity("Ts.DotCom.Domain.Models.PostImage", b =>
                {
                    b.HasOne("Ts.DotCom.Domain.Models.Post", "Post")
                        .WithOne("PostImage")
                        .HasForeignKey("Ts.DotCom.Domain.Models.PostImage", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Ts.DotCom.Domain.Models.PostRelative", b =>
                {
                    b.HasOne("Ts.DotCom.Domain.Models.Post", "Post")
                        .WithOne("PostRelative")
                        .HasForeignKey("Ts.DotCom.Domain.Models.PostRelative", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Ts.DotCom.Domain.Models.PostView", b =>
                {
                    b.HasOne("Ts.DotCom.Domain.Models.Post", "Post")
                        .WithOne("PostView")
                        .HasForeignKey("Ts.DotCom.Domain.Models.PostView", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Ts.DotCom.Domain.Models.StoryImage", b =>
                {
                    b.HasOne("Ts.DotCom.Domain.Models.Story", "Story")
                        .WithOne("StoryImage")
                        .HasForeignKey("Ts.DotCom.Domain.Models.StoryImage", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("Ts.DotCom.Domain.Models.StoryRelative", b =>
                {
                    b.HasOne("Ts.DotCom.Domain.Models.Story", "Story")
                        .WithOne("StoryRelative")
                        .HasForeignKey("Ts.DotCom.Domain.Models.StoryRelative", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("Ts.DotCom.Domain.Models.StoryView", b =>
                {
                    b.HasOne("Ts.DotCom.Domain.Models.Story", "Story")
                        .WithOne("StoryView")
                        .HasForeignKey("Ts.DotCom.Domain.Models.StoryView", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("Ts.DotCom.Domain.Models.Post", b =>
                {
                    b.Navigation("PostImage");

                    b.Navigation("PostRelative");

                    b.Navigation("PostView");
                });

            modelBuilder.Entity("Ts.DotCom.Domain.Models.Story", b =>
                {
                    b.Navigation("StoryImage");

                    b.Navigation("StoryRelative");

                    b.Navigation("StoryView");
                });
#pragma warning restore 612, 618
        }
    }
}
